config/routes.rb
Rails.application.routes.draw do
  get 'training/index'

  resources :exercises do
    resources :phases, only: :destroy
  end

  root 'exercises#index'
  get 'new' => 'exercises#new'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :phases, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :phases, allow_destroy: true, reject_if: proc { |phases| phases['action'].blank?}
end

app/models/phase.rb
class Phase < ActiveRecord::Base
  belongs_to :exercise

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercise = Exercise.new
    @phase = @exercise.phases.build

    @daysofweek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

    @monday = Exercise.includes(:phases).where("weekday = 1")
    @tuesday = Exercise.includes(:phases).where("weekday = 2")
    @wednesday = Exercise.includes(:phases).where("weekday = 3")
    @thursday = Exercise.includes(:phases).where("weekday = 4")
    @friday = Exercise.includes(:phases).where("weekday = 5")
    @saturday = Exercise.includes(:phases).where("weekday = 6")
    @sunday = Exercise.includes(:phases).where("weekday = 7")
    @data = []
    @data.push(@monday).push(@tuesday).push(@wednesday).push(@thursday).push(@friday).push(@saturday).push(@sunday)
  end
  def show
    @exercise = Exercise.find(params[:id])
  end
  def new
    @exercise = Exercise.new
    @phase = @exercise.phases.build
  end
  def edit
    @exercise = Exercise.find(params[:id])
  end
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
    redirect_to action: "index"
  end
  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.save
     redirect_to action: "index"
  end
  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      redirect_to action: "index"
    else
      render 'edit'
    end
  end

  private
    def exercise_params
      params.fetch(:exercise, {}).permit(:weekday, :description, phases_attributes: [:id, :action])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercise_helper.rb
module ExerciseHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/views/exercises/_form_create.html.erb
<p class="text-md-center">Add New Exercise</p>
<%= simple_form_for @exercise, url: exercises_path, :class => 'form-horizontal' do |f| %>
    <%= f.label :weekday%>
    <%=select(:exercise, :weekday, options_for_select([['Monday', 1],['Tuesday', 2],['Wednesday', 3],['Thursday', 4],['Friday', 5],['Saturday', 6],['Sunday', 7]])) %>
    <p>
      <%= f.label :description%>
      <%= f.text_area :description, :class => 'form-control' %>
    </p>
    <h5>Phases</h5>
    <%= f.simple_fields_for :phases do |pha| %>
        <div class="duplicatable-form">
          <%= pha.label :action %>
          <%= pha.text_field :action %>
          <%= link_to 'Remove', '', :remote => true, :class => 'dupli-destroy' %>
        </div>
    <% end %>
    <p>
      <%= link_to 'Add Phase', '', :class => 'duplicate-form' %>
    </p>
    <p>
      <%= f.submit :value => "Save Exercise", :class => 'btn btn-success' %>
    </p>
<% end %>

app/views/exercises/_weekly_schedule.html.erb
<p class="text-md-center">Weekly Schedule</p>
<% @daysofweek.each_with_index do |weekday, index| %>
<table class="table">
  <thead class="thead-inverse">
  <tr>
    <th><%= weekday %></th>
    <th>Phases</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @data[index].each do |exercise| %>
      <tr>
        <td><%= exercise.description %></td>
        <td>
          <% exercise.phases.all.each_with_index do |phase, index| %>
              <div class="inline"><%= index+1 %><span>: </span><%= phase.action %></div>
          <% end %>
        </td>
        <td style="width: 1em;">
          <%= link_to 'Edit', {action: "edit", id: exercise.id }, method: :get %>
          <%= link_to 'Remove', {action: "destroy", id: exercise.id }, method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/exercises/edit.html.erb
<p class="text-md-center">Edit Exercise</p>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <%= simple_form_for @exercise, url: exercise_path(@exercise), method: :patch, :class => 'form-horizontal' do |f| %>
          <%= f.label :weekday%>
          <%=select(:exercise, :weekday, options_for_select([['Monday', 1],['Tuesday', 2],['Wednesday', 3],['Thursday', 4],['Friday', 5],['Saturday', 6],['Sunday', 7]], f.object.weekday)) %>
          <p>
            <%= f.label :description%>
            <%= f.text_area :description, :class => 'form-control' %>
          </p>
          <h5>Phases</h5>
          <%= f.simple_fields_for :phases do |pha| %>
              <div class="duplicatable-form">
                <%= pha.label :action %>
                <%= pha.text_field :action %>
                <%= link_to 'Remove', exercise_phase_path(@exercise, pha.object), :method => :delete, :remote => true, :class => 'dupli-destroy' %>
                <%= pha.input :id, as: :hidden %>
              </div>
          <% end %>
          <p>
            <%= link_to 'Add Phase', '', :class => 'duplicate-form' %>
          </p>
          <p>
            <%= f.submit :value => "Save Exercise", :class => 'btn btn-success' %>
          </p>
      <% end %>
    </div>
  </div>
</div>

app/views/exercises/index.html.erb
<div class="container">
  <div class="row">
    <p class="text-lg-center">Weekly Training Program Manager</p>
  </div>
  <div class="row">
   <div class="col-lg-6">
     <%= render 'form_create' %>
   </div>
    <div class="col-lg-6">
      <%= render 'weekly_schedule' %>
    </div>
    </div>
  </div>
</div>

app/views/exercises/new.html.erb
<%= render 'form_create' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TamkRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>